### ISSUE TITLE
Change salinity parameters on NRS EOVs page

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/BioOceanObserver#188]
Once Leo has made the bottle salinity available in the NRS combined indices product, select this parameter for plotting rather than the CTD salinity.

**Comment by jaseeverett** [comment]
Has this been done @clairedavies ?

**Comment by jaseeverett** [comment]
Check `pr_get_EOVs` and it now uses `Salinity` rather than `CTDSalinity_PSU`
