### ISSUE TITLE
Extract usage stats

### ISSUE THREAD

**Issue by jaseeverett** [PlanktonTeam/BioOceanObserver#194]
Create markdown for building a monthly report of BOO access

**Comment by jaseeverett** [comment]
Can we work on this particular one next week @clairedavies. I would like to learn how to better access the website. At the same time we can write some code to automatically create the rmd. 
Perhaps we set up a meeting with Louise if you think it would help.

**Comment by clairedavies** [comment]
I don't think we can do this yet, looks like low priority for IM&T to allow us access to the data. 
Maybe we could up the priority with another eRCP proposal?

**Comment by clairedavies** [comment]
The biggest issue we have with elastic through and API is that the tokens that are required currently give access to way more information than is safe for users to have access to. I don’t have an access token, but Gareth has, so I haven’t tried it myself. I’ve been pushing for us developing a monitoring and reporting application on the web-app servers to present the information that any researcher monitoring their own app would need (with a way of filtering for the apps) and that way it means we don’t have to solve the token problem for individual researchers… unfortunately that has been deemed low priority for the group and the only way I’m going to be able to get it through as an action is by slipping it into another activity which has higher priorities than that.

In terms of the information that’s reported… the elasticstack dashboard should now be showing you all the fields that would be interesting (there are others that I didn’t put in) and there are visualisation capabilities in that tool (albeit limited) that seemed to suffice, considering the amount of info that’s recorded. Is there anything specific that you’re not seeing that you need there?

Email from Louise aug23

**Comment by jaseeverett** [comment]
Closing this for now. We have a basic app to display usage but elastic has now been cancelled by CSIRO so the path forward is unclear
