### ISSUE TITLE
download gets all data

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/BioOceanObserver#198]
This is your comment from the BOO tutorial at UQ, not sure what you meant by it.

**Comment by jaseeverett** [comment]
In most instances, the download data button gets the whole dataset for a given page, rather than the exact subset the user has selected. ie it won't be filtered by variable, site or date. I think the downloaded data should match exactly what is displayed.
Thoughts @clairedavies

**Comment by clairedavies** [comment]
Agree, that is what I thought it should do
