### ISSUE TITLE
What to do with WC samples and how do we document these things

### ISSUE THREAD

**Issue by clairedavies** [PlanktonTeam/BioOceanObserver#38]
How are we going to represent these in the plots, ignore them, assume a value ......
Whatever we does needs to be transparent so we are not misleading people.
This is a discussion we can have as we go along but isn't a show stopper.
ATM they have been filtered out.

**Comment by jaseeverett** [comment]
I will close this issue for now. I think we are passed this point. I will open a new issue for improving the documentation which is still sparse in the information tab
